### ISSUE TITLE
Visual bugs

### ISSUE THREAD

**Issue by snowei19** [ZenkakuHiragana/splatoonsweps#9] opened 2021-10-31 15:56 UTC
I was testing the new sub-weapons and noticed a few visual bugs.

https://youtu.be/pq7AloG21q0
and
![darkink](https://user-images.githubusercontent.com/48101518/139591666-b99c160f-f7b5-4956-abf6-d1e7c960fbfa.png)

Even with all addons disabled, the bugs still occur. I have no idea what what causes these bugs, but I'm guessing it's a problem with OpenGL.

Garry's Mod x86-64
OS : Fedora 34 x64 (linux)
GPU : Radeon RX 570 (8 GB)
CPU : Ryzen 7 3800xt

I don't know exactly how to reproduce these problems on Windows, but a launch option you can try is -r_emulate_gl. Hopefully that might help!

**Comment by ZenkakuHiragana** [comment] 2021-10-31 22:49
Thank you for posting and I confirmed the issue.
It seems some rendering features are missing in Linux ([Garry's Mod Issue #3926](https://github.com/Facepunch/garrysmod-issues/issues/3926)).  
I'm looking for a workaround, but I think it will be difficult.

Also, I did a quick workaround (that doesn't completely fix, though) for the second issue.

**Comment by ZenkakuHiragana** [comment] 2021-11-01 00:26
Applied a workaround and it seems to be fixed on Ubuntu 20.04 in WSL2.
It looks better, but more opaque than Windows instead.  
Windows:  
![image](https://user-images.githubusercontent.com/12111138/139606237-de4f1e44-2296-4fad-891c-25035f17cdf0.png)  
Linux:  
![image](https://user-images.githubusercontent.com/12111138/139606294-378f54e5-2a83-4294-9790-1ea188ac52dc.png)

**Closed by ZenkakuHiragana** 2021-11-01 00:26 UTC
Labels: bug
