### ISSUE TITLE
'You aren't ready to splat yet!' message appears on EVERY map

### ISSUE THREAD

**Issue by somedoodest** [ZenkakuHiragana/splatoonsweps#22] opened 2022-09-24 23:32 UTC
I don't know why, but for some reason, even though I seemingly deleted all data (both in main gmod folder and downloads folder) related to the addon before reinstalling it, the weapons broke for me on ALL maps, only displaying the 'You aren't ready to splat yet! Try again later!' message with any attempt to equip them and these two error messages.
[splatoonsweps] addons/splatoonsweps/lua/splatoonsweps/client/autorun.lua:134: attempt to index local 'dataTable' (a nil value)
    1. v - addons/splatoonsweps/lua/splatoonsweps/client/autorun.lua:134
        2. unknown - lua/includes/modules/hook.lua:96
[splatoonsweps] addons/splatoonsweps/lua/splatoonsweps/client/userinfo.lua:22: bad argument #1 to 'Compress' (string expected, got no value)
    1. Compress - [C]:-1
        2. v - addons/splatoonsweps/lua/splatoonsweps/client/userinfo.lua:22
            3. unknown - lua/includes/modules/hook.lua:96

**Comment by ZenkakuHiragana** [comment] 2022-10-02 10:08
I can't reproduce the issue but updated some things.  
Give me more details and see if it's (somehow) already fixed.

**Comment by somedoodest** [comment] 2022-10-02 11:15
Well, the updates did change the error that pops up. Still can't use the weapons, though. Here's the new error:
[splatoonsweps-master] addons/splatoonsweps-master/lua/splatoonsweps/server/network.lua:46: attempt to index local 'data' (a nil value)
    1. func - addons/splatoonsweps-master/lua/splatoonsweps/server/network.lua:46
        2. unknown - lua/includes/extensions/net.lua:33

**Comment by ZenkakuHiragana** [comment] 2022-10-02 12:25
Your circumstances are still unclear, but here are my thoughts:

1. DO NOT create dummy files.  Removing it is better.
2. Are you trying it on singleplayer or multiplayer?
  - If it's multiplayer, try removing the txt files on the server, too.

**Comment by somedoodest** [comment] 2022-10-02 13:21
Alright, so:
1. My circumstances are that I had a previous version of the addon installed, but I deleted everything in the garrysmod/data/splatoonsweps and garrysmod/download/data folders, and that's when the 'You aren't ready to splat yet!' message started appearing on every map with every weapon. The only thing that has generated in the addon's data folder after reinstalling is record/favorites.txt.
2. Alright. I created a dummy file as I thought this may be related to the addon not being able to create the file then write to it, so I decided to give it an empty file that it could potentially write to.
3. I am trying this on singleplayer.

**Comment by ZenkakuHiragana** [comment] 2022-10-02 17:04
It seems there must be Lua errors on map load.  If you have subscribed some unrelated addons, try disabling them and see the console.

**Comment by somedoodest** [comment] 2022-10-02 19:41
Huh, disabling addons did actually make it work. Don't know what broke it, but i'll try to figure that out.

**Comment by somedoodest** [comment] 2022-10-03 17:14
Well, I uninstalled the problem addon it seems, as I have not been recieving them ever since uninstalling it. It was [DRC] Halo Hunter Weapons (which is pretty buggy, so.. not surprised). Every lua error I've sent (except the AABBTree one) IS a startup error, with the network.lua one being the most up-to-date (as it happened after updating the addon yesterday, after more validity checks were added.)

**Comment by ZenkakuHiragana** [comment] 2022-10-03 18:30
What maps did you try?  I always try it on gm_construct but some special maps like Splatoon ports do not work well.

**Comment by somedoodest** [comment] 2022-10-03 19:45
Only gm_construct.

**Comment by ZenkakuHiragana** [comment] 2022-10-03 20:12
I still couldn't reproduce your issue but I fixed a bit around loading the map file.  
Anyway, is there any other info about the issue?

**Comment by somedoodest** [comment] 2022-10-03 20:15
Nope. Feel free to close this thread.

**Comment by ZenkakuHiragana** [comment] 2022-10-03 20:16
Sorry for not being able to help you.  Now I close this thread.

**Closed by ZenkakuHiragana** 2022-10-03 20:16 UTC
Labels: can't reproduce

**Comment by somedoodest** [comment] 2022-10-03 20:26
Meh, it's a rare addon conflict. Don't feel too bad about it, those tend to happen with complex stuff like this. Great work on the addon, btw.
